// Mock data for hackathons
const hackathons = [
  {
    id: 1,
    title: "Smart India Hackathon 2025",
    desc: "India's largest hackathon for students to solve problems faced by government, private sector, and NGOs.",
    date: "2025-08-15",
    mode: "Hybrid",
    sectorTags: ["All Sectors"],
    location: "Multiple Locations",
    organiser: "Ministry of Education",
  },
  {
    id: 2,
    title: "NASSCOM AI Gamechangers Hackathon",
    desc: "Build innovative AI solutions for real-world problems across industries.",
    date: "2025-07-10",
    mode: "Online",
    sectorTags: ["AI/ML", "Data Science"],
    location: "Virtual",
    organiser: "NASSCOM",
  },
  {
    id: 3,
    title: "Fintech Hackathon by NPCI",
    desc: "Develop innovative payment solutions using UPI, IMPS, and other NPCI platforms.",
    date: "2025-06-25",
    mode: "Offline",
    sectorTags: ["Fintech", "Blockchain"],
    location: "Mumbai",
    organiser: "NPCI",
  },
  {
    id: 4,
    title: "Agritech Innovation Challenge",
    desc: "Create technology solutions for Indian farmers and agricultural supply chain.",
    date: "2025-09-05",
    mode: "Hybrid",
    sectorTags: ["Agritech", "IoT"],
    location: "Delhi",
    organiser: "Ministry of Agriculture",
  },
  {
    id: 5,
    title: "Healthcare Innovation Hackathon",
    desc: "Develop solutions for affordable and accessible healthcare in India.",
    date: "2025-10-15",
    mode: "Offline",
    sectorTags: ["Healthtech", "Biotech"],
    location: "Bangalore",
    organiser: "BIRAC",
  },
  {
    id: 6,
    title: "Clean Energy Challenge",
    desc: "Build innovative solutions for renewable energy and sustainability.",
    date: "2025-11-20",
    mode: "Online",
    sectorTags: ["Clean Energy", "Sustainability"],
    location: "Virtual",
    organiser: "Ministry of New and Renewable Energy",
  },
  {
    id: 7,
    title: "Startup India Innovation Week Hackathon",
    desc: "Showcase innovative solutions across sectors during the Startup India Innovation Week.",
    date: "2025-05-30",
    mode: "Hybrid",
    sectorTags: ["All Sectors"],
    location: "Multiple Locations",
    organiser: "Startup India",
  },
  {
    id: 8,
    title: "Space Tech Challenge by ISRO",
    desc: "Develop applications and solutions using space technology and data.",
    date: "2025-08-30",
    mode: "Offline",
    sectorTags: ["Space Tech", "Data Science"],
    location: "Bangalore",
    organiser: "ISRO",
  },
  {
    id: 9,
    title: "Digital India EdTech Hackathon",
    desc: "Create innovative education technology solutions for Indian students.",
    date: "2025-07-25",
    mode: "Online",
    sectorTags: ["Edtech", "AI/ML"],
    location: "Virtual",
    organiser: "Ministry of Education",
  },
  {
    id: 10,
    title: "Blockchain for Governance Hackathon",
    desc: "Develop blockchain-based solutions for transparent governance.",
    date: "2025-09-15",
    mode: "Hybrid",
    sectorTags: ["Blockchain", "GovTech"],
    location: "Hyderabad",
    organiser: "Ministry of Electronics and IT",
  },
]

export async function GET() {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 800))

  return Response.json(hackathons)
}
